### ISSUE TITLE
一个关于数据集处理的问题

### ISSUE THREAD

**Issue by xsf777** [WingkeungM/RFFS-Net#5]
论文中提到你是讲数据集均匀分块进行处理，但是代码中确却是在随机的区域采样​4096个点，这是为什么​？​

**Comment by WingkeungM** [comment]
First, the limit of memory can only accept some points as the input of the network, so we choose to input 4096 or 2048 points to feed the network. Second, the block processing is to sample 4096 or 2048 points from each block. If sampling from the global area, it will lead to poor correlation between points.
