### ISSUE TITLE
How to process the data?

### ISSUE THREAD

**Issue by Yellowshuohahaha** [WingkeungM/RFFS-Net#6]
Could you release the code  or the processed data? Thanks a lot!

**Comment by WingkeungM** [comment]
The data preprocessing code has been uploaded, thank you for your attention. If you think our work has brought you help, please don't mean your star.

**Comment by Yellowshuohahaha** [comment]
After the training is completed, how to save the predicted results for the entire scene. Can you share the code？Thank you very much!

**Comment by SeanSiyang** [comment]
> After the training is completed, how to save the predicted results for the entire scene. Can you share the code？Thank you very much!

Have you solved the problem of data processing? Can I get an email in touch with you?

**Comment by Yellowshuohahaha** [comment]
@SeanSiyang Hi, just follwing the test.py and save the txt file will be all right.
